# Generated by Django 4.2.7 on 2023-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_details_digital_details_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.DecimalField(decimal_places=False, max_digits=10),
        ),
    ]
