# Generated by Django 4.2.5 on 2023-11-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_worksimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_images/')),
                ('slideproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.details')),
            ],
        ),
        migrations.DeleteModel(
            name='WorksImage',
        ),
    ]
