# Generated by Django 4.2.7 on 2023-11-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
    ]
