# Generated by Django 4.2.7 on 2023-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_user_profile_image/'),
        ),
    ]
