# Generated by Django 4.2.7 on 2023-11-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_review_review_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_user_image',
            field=models.ImageField(blank=True, null=True, upload_to=' /details/1/review_user_image/'),
        ),
    ]
