# Generated by Django 4.2.7 on 2023-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_review_review_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_user_image',
            field=models.ImageField(blank=True, null=True, upload_to=' review_user_image/'),
        ),
    ]
