# Generated by Django 4.2.7 on 2023-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
